# Generated by Django 4.2.20 on 2025-08-15 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_head_name', models.CharField(max_length=255)),
                ('number_of_men', models.PositiveIntegerField(default=0)),
                ('number_of_women', models.PositiveIntegerField(default=0)),
                ('household_head_phone_number', models.CharField(max_length=20)),
                ('village_street', models.CharField(max_length=255)),
                ('district', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.district')),
                ('hamlet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.hamlet')),
                ('region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.region')),
                ('veo', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.villagestreet')),
                ('ward', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.ward')),
            ],
        ),
    ]
