# Generated by Django 4.2.20 on 2025-08-15 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HamletHouseholdExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_households', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hamlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_expectations', to='locations.hamlet')),
            ],
        ),
    ]
